### ISSUE TITLE
2022-05-04 18-22-31.985 [Fatal] (onnx_ir_version) Model has multiple opset versions. This is legal, but really needs better documentation on what to do now.

### ISSUE THREAD

**Issue by zhangfeibao** [kraiskil/onnx2c#17]
I want to Know what  i can do to deal with it.thks

**Comment by kraiskil** [comment]
Hi zhangfeibao

That error message is a bit old, and written before onnx2c started to handle multiple opset versions.
Nowdays each onnx2c node / ONNX operand is handled separately, and everything should "just work".
So I think this error message can be downgraded to a `LOG(INFO)` level message.

**Comment by kraiskil** [comment]
Fixed in latest master.
