### ISSUE TITLE
fatal error: 'parseAttributes' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]

### ISSUE THREAD

**Issue by YJack0000** [kraiskil/onnx2c#34]
When compiling with c++ >= 11 will have this override error

**Comment by YJack0000** [comment]
#35

**Comment by kraiskil** [comment]
Interesting. The top level CMakeListst.txt does specify C++11.
I've compiled with both GCC and Clang, and don't see this warning/error. Which compiler are you using?

**Comment by YJack0000** [comment]
Sorry for the mis understanding of the problem. 
I initially thought it is a CXX version problem because I saw someone on the Internet saying that inconsistent-missing-override is a new thing in C++11.

After trying on different devices, I found that it can compiled successfully in C++11 on my linux laptop. 

So, I think the problem might be from xcode, because the compiler that I'm using to get that error is the one in the image below. 
<img width="888" alt="Screenshot 2023-09-13 at 7 22 45 PM" src="https://github.com/kraiskil/onnx2c/assets/49984479/79009416-3a1b-4afd-b44d-1b39ac55d08d">

And the error log is 
<img width="1266" alt="Screenshot 2023-09-13 at 7 35 15 PM" src="https://github.com/kraiskil/onnx2c/assets/49984479/7e0401d2-43a7-4772-b719-d6510c03f0fb">

**Comment by kraiskil** [comment]
Ok, that clang looks fairly recent. I've tried with Clang 10 or so, if memory serves.

The main problem is the -Werror flag that converts even fairly benign warnings like this into fatal errors. But that flag keeps the build clean, so sometimes small fixes like this are needed.

Thanks for the fix :)
