### ISSUE TITLE
error: comparison of integer expressions of different signedness

### ISSUE THREAD

**Issue by AhmedKishki** [kraiskil/onnx2c#62]
I get the following error as I follow the installation for onnx2c:

> (base) kishki@DETENNB346:~/testing/onnx2c/build$ make onnx2c
> -- Failed to find LLVM FileCheck
> -- git version: v1.7.0-10-g77d1e74d normalized to 1.7.0.10
> -- Version: 1.7.0.10
> -- Performing Test HAVE_STD_REGEX -- success
> -- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
> -- Performing Test HAVE_POSIX_REGEX -- success
> -- Performing Test HAVE_STEADY_CLOCK -- success
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/kishki/testing/onnx2c/build
> [  0%] Built target clear_cache
> Consolidate compiler generated dependencies of target timestamp
> [  0%] Building C object cmake_timestamp/CMakeFiles/timestamp.dir/timestamp.c.o
> [  0%] Built target timestamp
> Consolidate compiler generated dependencies of target onnx2c_lib
> [  0%] Building CXX object CMakeFiles/onnx2c_lib.dir/src/nodes/reducemean.cc.o
> /home/kishki/testing/onnx2c/src/nodes/reducemean.cc: In member function ‘virtual void toC::ReduceMean::print(std::ostream&) const’:
> /home/kishki/testing/onnx2c/src/nodes/reducemean.cc:183:31: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int64_t’ {aka ‘long int’} [-Werror=sign-compare]
>   183 |                         if (i == axis)
>       |                             ~~^~~~~~~
> compilation terminated due to -Wfatal-errors.
> cc1plus: all warnings being treated as errors
> make[3]: *** [CMakeFiles/onnx2c_lib.dir/build.make:293: CMakeFiles/onnx2c_lib.dir/src/nodes/reducemean.cc.o] Error 1
> make[2]: *** [CMakeFiles/Makefile2:1258: CMakeFiles/onnx2c_lib.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:1292: CMakeFiles/onnx2c.dir/rule] Error 2
> make: *** [Makefile:192: onnx2c] Error 2

**Comment by XaverFink** [comment]
As a workaround you can add 

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-sign-compare")`

to your CMakeLists.txt

**Comment by tlane-rbx** [comment]
Sorry, my bad. D:
