### ISSUE TITLE
Convolution bias bug

### ISSUE THREAD

**Issue by mrzealot** [kraiskil/onnx2c#7]
Hi! Was tinkering with the converter and found a bug on [this line](https://github.com/kraiskil/onnx2c/blob/a7b27e48a3dabb6e68933eb5652cfa4f6b16d6e1/src/nodes/conv.h#L222). Seems like the bias addition is indexed along the incorrect dimension (I think it should be `[m]` instead of `[b]`). Just a heads up...

**Comment by kraiskil** [comment]
Yeah, that does indeed look like it should be `[m]`. Would you happen to have a nice small test case to trigger this?

**Comment by mrzealot** [comment]
Nah, sorry, just a huge (thereby not very helpful, and unfortunately also non-public) input, after which I was just glad to have found the problem. But any mini example with a multi-map kernel will probably do...

**Comment by kraiskil** [comment]
Fixed now, thanks for the detective work!
